# archivo mosquitto.conf
# para curso dis9079
# v0.0.1
# febrero 2026
listener 1883 10.24.242.179     
protocol mqtt
accept_protocol_versions 3,4,5
allow_anonymous true
allow_zero_length_clientid false
connection_messages true
global_max_connections 50
# log_dest file ./log.txt
log_dest file stdout
log_type all
password_file ./passwords.txt
# use_username_as_clientid true